apiVersion: v2
name: backstage
description: Backstage app provided by Giant Swarm
home: https://github.com/giantswarm/backstage
version: 0.95.1
appVersion: '0.95.1'
annotations:
  io.giantswarm.application.team: honeybadger
  io.giantswarm.application.logo: https://s.giantswarm.io/app-icons/backstage/1/logo.svg
icon: https://s.giantswarm.io/app-icons/backstage/1/icon.svg
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.31.4
